version: 2
updates:
  # Check for outdated Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    target-branch: "dev"
    labels:
      - "dependencies"
