name: Garbage Collection

on:
  schedule:
    - cron: '08 10 * * 1'

  workflow_dispatch:
    inputs:
      days:
        description: 'Retention Period (in days)'
        required: true
        default: '30'

permissions:
  actions: write
  attestations: read
  checks: read
  contents: read
  deployments: read
  id-token: none
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: 'Delete outdated workflow runs'
        uses: Mattraks/delete-workflow-runs@v2.0.6

        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          RETAIN_DAYS: ${{ github.event.inputs.days }}

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ env.GITHUB_REPOSITORY }}
          retain_days: ${{ env.RETAIN_DAYS }}
          keep_minimum_runs: 5
